name: ReadingList
targets:
  ReadingList:
    type: application
    platform: iOS
    deploymentTarget: 10.3
    sources: [ReadingList]
    scheme:
      testTargets:
        - ReadingList_UnitTests
        - ReadingList_UITests
        - ReadingList_Screenshots
    dependencies:
      - framework: StoreKit.framework
        embed: false
      - target: ReadingList_Foundation
    preBuildScripts:
      - name: SwiftLint
        script: |
                if [[ -z $CI ]]; then
                  "/usr/local/bin/swiftlint" --path "${PROJECT_DIR}"
                fi
    postBuildScripts:
      - name: "[CP] Embed Pods Frameworks"
        script:
      - name: Run Fabric Script
        inputFiles: [$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)]
        path: build/fabric.sh
    settings:
      base:
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: $(inherited)
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_ENTITLEMENTS: ReadingList/ReadingList.entitlements
        DEVELOPMENT_TEAM: YPDEV2E775
        PRODUCT_BUNDLE_IDENTIFIER: com.andrewbennet.books
      configs:
        Debug:
          PROVISIONING_PROFILE_SPECIFIER: match Development com.andrewbennet.books
          OTHER_SWIFT_FLAGS: $(inherited) "-D" "DEBUG"
        Release:
          PROVISIONING_PROFILE_SPECIFIER: match AppStore com.andrewbennet.books
          CODE_SIGN_IDENTITY[sdk=iphoneos*]: "iPhone Distribution: Andrew Bennet (YPDEV2E775)"
          OTHER_SWIFT_FLAGS: $(inherited) "-D" "RELEASE"
    attributes:
      SystemCapabilities:
        com.apple.iCloud:
          enabled: 1
        com.apple.InAppPurchase:
          enabled: 1
  ReadingList_Foundation:
    type: framework
    platform: iOS
    deploymentTarget: 10.3
    sources: [ReadingList_Foundation]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.andrewbennet.ReadingList-Foundation
  ReadingList_UnitTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 10.3
    sources: [ReadingList_UnitTests]
    dependencies:
      - target: ReadingList
    settings:
      # These settings are added when Xcode creates a new project with test targets.
      # See https://stackoverflow.com/a/30939244/5513562
      BUNDLE_LOADER: $TEST_HOST
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/ReadingList.app/ReadingList
  ReadingList_UITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: 10.3
    sources: [ReadingList_UITests]
    dependencies:
      - target: ReadingList
  ReadingList_Screenshots:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: 10.3
    sources:
      - path: ReadingList_Screenshots
      - path: ReadingList_UITests/ReadingListApplication.swift
    dependencies:
      - target: ReadingList
    scheme:
      testTargets:
        - ReadingList_Screenshots
options:
  groupSortPosition: top
