default_platform(:ios)
xcversion(version: "10.1")

platform :ios do

  desc "Configures Fabric, builds the project file and sets the build number from git."
  lane :preprocess do
    sh "./configure_fabric.sh"
    sh "cd .. && mint run yonaskolb/xcodegen"
    sh "cd .. && pod install"
    increment_build_number(build_number: number_of_commits)
  end

  lane :ci do
    test
    configure_keychain
    build_app(workspace: "ReadingList.xcworkspace", scheme: "ReadingList")
  end

  lane :test do
    # run tests synchronously as a bug in xcpretty will hide test results when multiple devices are used
    scan(
      scheme: "ReadingList",
      devices: ["iPhone 8 (11.4)", "iPad Pro (10.5-inch) (11.4)"],
      disable_concurrent_testing: true
    )
  end

  desc "Uploads the previously built binary to TestFlight and tags it"
  lane :upload_build do
    upload_to_testflight(skip_submission: true, skip_waiting_for_build_processing: true)
  end

  desc "Creates and pushes a tag like 'build/1583'"
  lane :tag_build do
    build_tag = "build/" + get_build_number.to_s
    add_git_tag(
      tag: build_tag
    )
    sh("git push https://AndrewBennet:$GITHUB_TOKEN@github.com/AndrewBennet/ReadingList.git tag " + build_tag)
  end

  lane :release do |options|
    deliver(
      build_number: options[:build_number],
      app_version: options[:version],
      automatic_release: false
    )
    add_git_tag(
      tag: "v" + options[:version]
    )
  end

  desc "Create framed screenshots for a range of devices"
  lane :snaps do
    snapshot
    frame_screenshots(white: true)
  end

  desc "Download DSYMs from iTunes and upload them to Crashlytics"
  lane :dsyms do
    download_dsyms(version: "latest")
    upload_symbols_to_crashlytics
    clean_build_artifacts
  end

  private_lane :configure_keychain do
    # From https://docs.travis-ci.com/user/common-build-problems/#Mac%3A-macOS-Sierra-(10.12)-Code-Signing-Errors
    create_keychain(
      name: 'tmp_ci_keychain',
      password: 'tmp_ci_keychain_password',
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
    sh("git config --global credential.helper osxkeychain")
    sh("git clone https://AndrewBennet:$GITHUB_TOKEN@github.com/AndrewBennet/certificates.git")
    sh("rm -rf certificates")
    match(
      type: "appstore",
      keychain_name: 'tmp_ci_keychain',
      keychain_password: 'tmp_ci_keychain_password',
      readonly: true
    )
  end

  desc "Create a commit incrementing the patch number"
  lane :patch do
    increment_version_number(bump_type: "patch")
  end

  desc "Create a commit incrementing the minor version number"
  lane :minor do
    increment_version_number(bump_type: "minor")
  end

  desc "Create a commit incrementing the major version number"
  lane :major do
    increment_version_number(bump_type: "major")
  end

end
