# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Run tests"
  lane :test do
    cocoapods
    # run tests synchronously as a bug in xcpretty will hide test results when multiple devices are used
    scan(scheme: "ReadingList", devices: ["iPhone 7 (10.3.1)"])
    scan(scheme: "ReadingList", devices: ["iPhone 8"], test_without_building: true)
    scan(scheme: "ReadingList", devices: ["iPad Pro (10.5-inch) (11.2)"], test_without_building: true)
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    if is_ci
      sh("travis-setup.sh")
    end
    match
    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })
    build_app(workspace: "ReadingList.xcworkspace", scheme: "ReadingList")
    upload_to_testflight
  end

  desc "Download DSYMs from iTunes and upload them to Crashlytics"
  lane :dsyms do
    download_dsyms
    upload_symbols_to_crashlytics
    clean_build_artifacts
  end
end
