devices([
	"iPhone SE",
	"iPhone 8",
	"iPhone 8 Plus",
	"iPhone X",
	"iPad Pro (9.7-inch)",
	"iPad Pro (12.9-inch)"
])
languages([
  "en-US"
])
scheme("Screenshots")
output_directory("../ReadingList_Screenshots")
workspace("ReadingList.xcworkspace")
clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
